[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "daphne -b 0.0.0.0 -p $PORT main:app"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
ATLAS_ENV = "production"
LOG_LEVEL = "INFO"
PROMETHEUS_ENABLED = "true"
